[build]
  command = """
  set -eo pipefail
  corepack pnpm install
  corepack pnpm build
  corepack pnpm lint && git diff --exit-code
  curl -fsLS https://gist.githubusercontent.com/yoursunny/54db5b27f9193859b7d1c83f0aeb8d6d/raw/ca-profile.data.base64 | base64 -d > public/profile.data
  """
  publish = "public/"

[build.environment]
  NODE_VERSION="17"
  NPM_FLAGS="--version"
